AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  CobblerRecipesService:
    Type: AWS::Serverless::Api
    Description: "Serverless API for CRUD operations"
    Properties:
      Name: "cobbler-recipes-service"
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS, POST, GET, PUT, DELETE'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'http://localhost:3000'" # replace with frontend app URL

  CobblerRecipesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: bootstrap
      Runtime: provided.al2023
      Policies:
        - AWSLambdaExecute
        - SecretsManagerReadWrite
        - DynamoDBCrudPolicy:
            TableName: !Ref CobblerRecipesTable
      Events:
        RecipesOptions:
          Type: Api
          Properties:
            Path: /recipes
            Method: OPTIONS
            RestApiId: !Ref CobblerRecipesService
        GetRecipe:
          Type: Api
          Properties:
            Path: /recipes/{id}
            Method: GET
            RestApiId: !Ref CobblerRecipesService
        GetRecipes:
          Type: Api
          Properties:
            Path: /recipes
            Method: GET
            RestApiId: !Ref CobblerRecipesService
        PutRecipe:
          Type: Api
          Properties:
            Path: /recipes
            Method: POST
            RestApiId: !Ref CobblerRecipesService
        DeleteRecipe:
          Type: Api
          Properties:
            Path: /recipes/{id}
            Method: DELETE
            RestApiId: !Ref CobblerRecipesService
        UpdateRecipe:
          Type: Api
          Properties:
            Path: /recipes/{id}
            Method: PUT
            RestApiId: !Ref CobblerRecipesService
    Metadata:
      BuildMethod: makefile

  CobblerRecipesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CobblerRecipes
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
