AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  CobblerRecipesService:
    Type: AWS::Serverless::Api
    Description: "Serverless API for CRUD operations"
    Properties:
      Name: "cobbler-recipes-service"
      StageName: Prod
      Auth:
        DefaultAuthorizer: AWS_IAM
        InvokeRole: NONE  

      Cors:
        AllowMethods: "'OPTIONS, POST, GET, PUT, DELETE'"
        AllowHeaders: "'Content-Type, x-amz-content-sha256, x-amz-date, X-Amz-Security-Token, Authorization'"
        # AllowOrigin: "'http://localhost:5173'" # replace for production
        AllowOrigin: "'https://cobbler.phil-code.com'"
        AllowCredentials: true

      # Logging settings
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: "/*"
          HttpMethod: "*"
          MetricsEnabled: true
          DataTraceEnabled: true
      AccessLogSetting:
        DestinationArn: 
          Fn::GetAtt:
            - CobblerRecipesLogGroup
            - Arn
        Format: '$context.identity.sourceIp $context.identity.caller $context.identity.user [$context.requestTime] "$context.httpMethod $context.resourcePath $context.protocol" $context.status $context.responseLength $context.requestId'

  CobblerRecipesLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/api-gateway/${CobblerRecipesService}"
      RetentionInDays: 7    

  CobblerRecipesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: bootstrap
      Runtime: provided.al2023
      MemorySize: 512
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref CobblerRecipesTable
      Events:
        RecipesOptions:
          Type: Api
          Properties:
            Path: /recipes
            Method: OPTIONS
            RestApiId: !Ref CobblerRecipesService
            Auth:
              Authorizer: NONE
        RecipesOptionsId:
          Type: Api
          Properties:
            Path: /recipes/{id}
            Method: OPTIONS
            RestApiId: !Ref CobblerRecipesService
            Auth:
              Authorizer: NONE
        GetRecipe:
          Type: Api
          Properties:
            Path: /recipes/{id}
            Method: GET
            RestApiId: !Ref CobblerRecipesService
        GetRecipes:
          Type: Api
          Properties:
            Path: /recipes
            Method: GET
            RestApiId: !Ref CobblerRecipesService
            RequestParameters:
              method.request.querystring.q:
                Required: false
                Caching: false
        PutRecipe:
          Type: Api
          Properties:
            Path: /recipes
            Method: POST
            RestApiId: !Ref CobblerRecipesService
        DeleteRecipe:
          Type: Api
          Properties:
            Path: /recipes/{id}
            Method: DELETE
            RestApiId: !Ref CobblerRecipesService
        UpdateRecipe:
          Type: Api
          Properties:
            Path: /recipes/{id}
            Method: PUT
            RestApiId: !Ref CobblerRecipesService
    Metadata:
      BuildMethod: makefile

  CobblerRecipesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CobblerRecipes
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
