AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ApiKeyValue:
    Type: String
    NoEcho: true
    Description: "API Key for the CobblerRecipesService"

Resources:
  CobblerRecipesService:
    Type: AWS::Serverless::Api
    Description: "Serverless API for CRUD operations"
    Properties:
      Name: "cobbler-recipes-service"
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS, POST, GET, PUT, DELETE'"
        AllowHeaders: "'Content-Type, x-api-key'"
        AllowOrigin: "'http://localhost:3000'" # replace for production
      Auth:
        ApiKeyRequired: true

  CobblerRecipesApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn: CobblerRecipesServiceProdStage
    Properties:
      Name: "CobblerRecipesApiKey"
      Enabled: true
      Value: !Ref ApiKeyValue
      StageKeys:
        - RestApiId: !Ref CobblerRecipesService
          StageName: Prod

  CobblerRecipesUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: CobblerRecipesServiceProdStage
    Properties:
      UsagePlanName: "CobblerRecipesUsagePlan"
      ApiStages:
        - ApiId: !Ref CobblerRecipesService
          Stage: Prod
      Throttle:
        RateLimit: 100
        BurstLimit: 20
      Quota:
        Limit: 10000
        Period: MONTH

  CobblerRecipesUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref CobblerRecipesApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref CobblerRecipesUsagePlan

  CobblerRecipesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: bootstrap
      Runtime: provided.al2023
      MemorySize: 512
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref CobblerRecipesTable
      Events:
        RecipesOptions:
          Type: Api
          Properties:
            Path: /recipes
            Method: OPTIONS
            RestApiId: !Ref CobblerRecipesService
            Auth:
              ApiKeyRequired: false
        RecipesOptionsId:
          Type: Api
          Properties:
            Path: /recipes/{id}
            Method: OPTIONS
            RestApiId: !Ref CobblerRecipesService
            Auth:
              ApiKeyRequired: false
        GetRecipe:
          Type: Api
          Properties:
            Path: /recipes/{id}
            Method: GET
            RestApiId: !Ref CobblerRecipesService
            Auth:
              ApiKeyRequired: true
        GetRecipes:
          Type: Api
          Properties:
            Path: /recipes
            Method: GET
            RestApiId: !Ref CobblerRecipesService
            Auth:
              ApiKeyRequired: true
        PutRecipe:
          Type: Api
          Properties:
            Path: /recipes
            Method: POST
            RestApiId: !Ref CobblerRecipesService
            Auth:
              ApiKeyRequired: true
        DeleteRecipe:
          Type: Api
          Properties:
            Path: /recipes/{id}
            Method: DELETE
            RestApiId: !Ref CobblerRecipesService
            Auth:
              ApiKeyRequired: true
        UpdateRecipe:
          Type: Api
          Properties:
            Path: /recipes/{id}
            Method: PUT
            RestApiId: !Ref CobblerRecipesService
            Auth:
              ApiKeyRequired: true
    Metadata:
      BuildMethod: makefile

  CobblerRecipesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CobblerRecipes
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
